spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email


  jpa:
    hibernate:
      ddl-auto: update        # 테이블 자동 생성/업데이트
    show-sql: true

jwt:
  secret: ${JWT_SECRET} # Base64
  expiration: 86400000        # 24시간
  refresh-expiration: 604800000 # 7일

server:
  port: 8080

frontend:
  url: ${FRONTEND_URL}


